version: '3'

services:

  web:
    image: node:14
    container_name: nginx

    command: >
      bash -c "yarn install
      && yarn serve"

    ports:
      - '3000:3000'
      # - '8080:8080'

    volumes:
       - ./dev/darksdk/:/usr/share/nginx/html:delegated

    working_dir: /usr/share/nginx/html