version: '3'
services:
  node:
    container_name: node
    image: dscr/node:14-alpine
    ports:
      - '3000:3000'

    volumes:
       - ./packages/sdk/:/node/app:delegated
       - ./packages/sdk/node_modules:/node/node_modules:delegated

    working_dir: /node/app